- app/src/main/java/com/cpr3663/cpr_scouting_app/AppLaunch.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/Match.java
Made the Context Menus display the correct events.
> Context Menu using correct Data

- app/src/main/java/com/cpr3663/cpr_scouting_app/AppLaunch.java
my bad.
missing "}"
and had:
settext(getResources().getColor(R.string.banner_app_name))
instead of:
settext(getResources().getString(R.string.banner_app_name))
the run-time error was nasty hard to figure out.
> fix broken build

- .idea/.name
- .idea/deploymentTargetSelector.xml
- .idea/misc.xml
- .idea/other.xml
- README.md
- app/src/main/java/com/cpr3663/cpr_scouting_app/AppLaunch.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/Match.java
- app/src/main/res/layout/match.xml
Fixed a bunch of misspelled words. Also Improved how some if statements worked when checking if strings are equal.
> Misspellings and Robustness

- .idea/deploymentTargetSelector.xml
- .idea/other.xml
- app/src/main/assets/input_data/Events_Teleop.csv
- app/src/main/java/com/cpr3663/cpr_scouting_app/AppLaunch.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/Competitions.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/Constants.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/DNPs.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/Devices.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/Events.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/Globals.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/Match.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/Matches.java
moved app-level classes to their own file (standardized on naming for my classes)
created a Globals class
created a Constants class
patched all references to classes/globals/constants
> Refactored project files to Java best-practices

- .idea/deploymentTargetSelector.xml
- app/src/main/assets/input_data/Comments.csv
- app/src/main/java/com/cpr3663/cpr_scouting_app/AppLaunch.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/Comments.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/Competitions.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/DNPs.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/Devices.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/Events.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/Globals.java
- app/src/main/res/layout/match.xml
- app/src/main/res/layout/pre_match.xml
- app/src/main/res/values/datafiles.xml
- app/src/main/res/values/strings.xml
Forgot about needing this for post-match activity.
> Added Comment Class

- app/src/main/java/com/cpr3663/cpr_scouting_app/AppLaunch.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/Competitions.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/Devices.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/Match.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/Matches.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/PreMatch.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/Settings.java
- app/src/main/res/layout/pre_match.xml
- app/src/main/res/layout/settings.xml
Made it so that in Settings and PreMatch when you type in a team number, match number, device Id, or Competition Id it pops up the name of it. Also fixed up the code so that it doesn't keep adding lines, wait for no reason, or have a possibility of the data getting messed up. Also marked the places where we need the logger in Match with a TODO.
> Name popup and autofill team number

- app/src/main/java/com/cpr3663/cpr_scouting_app/AppLaunch.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/Globals.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/PreMatch.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/Settings.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/data/ClimbPositions.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/data/Comments.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/data/Competitions.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/data/DNPs.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/data/Devices.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/data/Events.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/data/Matches.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/data/StartPositions.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/data/TrapResults.java
- app/src/main/res/values/datafiles.xml
- app/src/main/res/values/strings.xml
Also moved data classes into their own package to keep them isolated from other code (organization)
> Robust loading of data for 3 new data classes

- app/src/main/java/com/cpr3663/cpr_scouting_app/Constants.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/Logger.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/PostMatch.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/PreMatch.java
- app/src/main/res/layout/pre_match.xml
- app/src/main/res/values/strings.xml
Now we will write out a short header row in the CSV files.
> log header rows and allow re-submit data bypass

- app/src/main/java/com/cpr3663/cpr_scouting_app/Match.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/PostMatch.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/PreMatch.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/data/ClimbPositions.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/data/Comments.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/data/DNPs.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/data/StartPositions.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/data/TrapResults.java
Also fixed a bug with the auto fill match number and some of the comments. Also made the data classes have a function called getDescriptionList, which gets a string array of all of the available descriptions.
> Comments and DNP use data classes

- app/src/main/res/layout/post_match.xml
- app/src/main/res/layout/pre_match.xml
- app/src/main/res/layout/submit_data.xml
- app/src/main/res/values/strings.xml
fixed a spinner background to see if it works in .xml (it does).  
fixed sizing of other boxes on post/submit pages (not a filed issue) to be more in line with the other pages.
> Fix Issue #127

- app/src/main/java/com/cpr3663/cpr_scouting_app/Constants.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/Match.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/PreMatch.java
- app/src/main/res/layout/pre_match.xml
- app/src/main/res/values/strings.xml
Added the checkbox for Start Note and made it log it and have the correct context menu options on your first click.
Closes #90
> Starting Note

- app/src/main/java/com/cpr3663/cpr_scouting_app/PreMatch.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/SubmitData.java
- app/src/main/res/layout/pre_match.xml
- app/src/main/res/layout/submit_data.xml
- app/src/main/res/values/strings.xml
Fixed bug for Team Name not left-aligned on PreMatch page.
Changed position of "resubmit data" 
Added searching output (logger) files on submit page and preload "select match" spinner to be based on these.
I also create the spinner from an ArrayList<> not from a static list.  You can copy the code for the others, if needed.
> 2 bugs fixes + added automatic match dropdown on Submit page

- app/src/main/java/com/cpr3663/cpr_scouting_app/AppLaunch.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/PostMatch.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/PreMatch.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/Settings.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/SubmitData.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/data/Competitions.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/data/Devices.java
- app/src/main/res/layout/post_match.xml
- app/src/main/res/layout/pre_match.xml
- app/src/main/res/layout/settings.xml
- app/src/main/res/values/strings.xml
added needed functions to Data Classes and changed device_number to id like all the other classes (consistency).
fixed up some layout.xml files (start instead of left, etc)
made the splash screen faster (we're loading enough data now we don't need to slow down TOO much)
converted some of the edit_text to spinners.
in submitdata.java got ride of matches_list since it wasn't needed as in intermediary and just taking up RAM.
> dropdowns all use input_data files rather than hard-coding

- app/src/main/java/com/cpr3663/cpr_scouting_app/AppLaunch.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/Logger.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/Match.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/PostMatch.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/PreMatch.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/Settings.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/SubmitData.java
Reduced code needed to getString() - we don't need the getResources() before it.
Properly close off the logger files if we deselect "Did they Play?" Removed some TODO's
Loading input files no longer use hard coded strings. Fixed Header in "d" file for D_Key instead of E_Key (oops)
> fixed / protected input files

- .idea/inspectionProfiles/Project_Default.xml
- app/src/main/java/com/cpr3663/cpr_scouting_app/PostMatch.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/PreMatch.java
Some of the logger code was commented, they were from when the weren't dropdowns and they weren't uncommented when converted to dropdowns.
fixes #160
> Uncommented Log code

- app/src/main/assets/input_data/StartPositions.csv
- app/src/main/java/com/cpr3663/cpr_scouting_app/AppLaunch.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/Constants.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/PreMatch.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/data/StartPositions.java
It is now required to continue and will cause a toast message, did not play isn't an option, will be overridden with did not play if that is the case, and is by default "Choose one".
Fixes #151
> Start Position Fix

- app/src/main/java/com/cpr3663/cpr_scouting_app/Logger.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/Match.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/PreMatch.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/data/Colors.java
- gradle.properties
> Reset logging sequence numbers in-between matches

- app/src/main/java/com/cpr3663/cpr_scouting_app/Logger.java
- app/src/main/res/values/strings.xml
Because the strings.xml auto trims its strings I got rid of the space so that it won't confuse/trick anyone into not adding a space in. And made the logger more efficient and commented it.
> String and logger fix

- app/src/main/assets/input_data/Competitions.csv
- app/src/main/java/com/cpr3663/cpr_scouting_app/AppLaunch.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/Globals.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/Settings.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/data/ClimbPositions.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/data/Colors.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/data/Comments.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/data/Competitions.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/data/Devices.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/data/Events.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/data/Matches.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/data/StartPositions.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/data/TrapResults.java
- app/src/main/res/drawable/scrollbar_style.xml
- app/src/main/res/layout/settings.xml
> Reload match data if you change the competitionID in settings.

- app/src/main/java/com/cpr3663/cpr_scouting_app/PreMatch.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/data/Matches.java
The logic of making sure a inputted number wasn't out of bounds was messed up and didn't work. Also some of the comments weren't changed when copy and pasted.
Fixes #207
> Comments and fixed/better logic

- app/src/main/assets/input_data/Events_Auto.csv
- app/src/main/assets/input_data/Events_Teleop.csv
- app/src/main/java/com/cpr3663/cpr_scouting_app/Constants.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/Logger.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/Match.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/data/Events.java
- app/src/main/res/layout/match.xml
- app/src/main/res/values/strings.xml
Blinking is now "Erica" style
Log X/Y are now WHOLE numbers
Log Time is now 1 decimal point.
Log StartTime in "d" file to help with de-duping.
also cleaned up Match layout (centered buttons vertically, padding, etc.)
got rid of "Time:" and just show the countdown clock.  saves room.
> Fix 4 issues

- app/build.gradle.kts
- app/release/output-metadata.json
- app/src/main/java/com/cpr3663/cpr_scouting_app/AppLaunch.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/Globals.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/Logger.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/Match.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/PreMatch.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/data/Events.java
- app/src/main/res/layout/app_launch.xml
- app/src/main/res/layout/match.xml
- app/src/main/res/layout/pre_match.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
Practice mode was causing problems (crash) if you hit BACK and then didn't practice.
Removed "STATIC" from Logger class variables - they shouldn't have been from the get-go.
Cleaned up other BACK button mis-behavior with the logger (check for null before creating a new one, clear out data before starting to log more)
Made more room in the Match xml for larger status text, ensure timer is large enough, etc.
Additional logging (TOAST msg) in logger when things don't go as expected.
> Fixes for Bordie

- app/src/main/java/com/cpr3663/cpr_scouting_app/Logger.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/Match.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/PreMatch.java
- app/src/main/java/com/cpr3663/cpr_scouting_app/data/Events.java
- app/src/main/res/layout/match.xml
- app/src/main/res/values/strings.xml
Events: needed some helper functions here and fixed some warnings on final and private things
Logger: helper functions to undo actions.
isLastEventAnOrphan() is going to be used to fix another upcoming bug.  Ignore that for now, but you can review it.
Match: added undo button with onClick actions.  Also moved matchControl changes in UIThread.
Pre-Match: added "0" time for startingnote (read comment in code)
XML: layout changes, string changes.
> UNDO actions now!

- .idea/other.xml
- app/src/main/java/com/team3663/scouting_app/activities/AppLaunch.java
- app/src/main/java/com/team3663/scouting_app/activities/Match.java
- app/src/main/java/com/team3663/scouting_app/activities/PostMatch.java
- app/src/main/java/com/team3663/scouting_app/activities/PreMatch.java
- app/src/main/java/com/team3663/scouting_app/activities/Settings.java
- app/src/main/java/com/team3663/scouting_app/activities/SubmitData.java
- app/src/main/java/com/team3663/scouting_app/config/Constants.java
- app/src/main/java/com/team3663/scouting_app/config/Globals.java
- app/src/main/java/com/team3663/scouting_app/data/Comments.java
- app/src/main/java/com/team3663/scouting_app/data/Events.java
- app/src/main/java/com/team3663/scouting_app/data/Matches.java
- app/src/main/java/com/team3663/scouting_app/utility/Achievements.java
- app/src/main/java/com/team3663/scouting_app/utility/Logger.java
Mostly refactored all of the onCreates to call a number of functions to do all of the initializing.  This makes onCreate WAY easier to read and encapsulates each component functionality into its own function.  This looks messy but I just MOVED code from onCreate to the function.
Changed the way we call (and return) from Settings page.  This is WAY nicer and the way Android is meant to do it.
Added the skeleton for Achievements to pop up.  It's all ignored right now.
Also fixed a few bugs (see list)
teamToScout spinner - the loadTeamData() was mostly a re-write to handle all situations.  We had this code in 3-4 different spots in the activity.  really hard to debug.
> Last of the refactoring - coding standards

- app/src/main/java/com/team3663/scouting_app/activities/Match.java
- app/src/main/res/values/strings_match.xml
> Handle orphaned events at the end of the match

- app/src/main/java/com/team3663/scouting_app/activities/PostMatch.java
It now JUST clears the selected/checked items.
fixes #130
> Comment "Clear list" doesn't close the dialog

- app/release/output-metadata.json
- app/src/main/assets/input_data/Comments.csv
- app/src/main/java/com/team3663/scouting_app/activities/AppLaunch.java
- app/src/main/java/com/team3663/scouting_app/activities/Match.java
- app/src/main/java/com/team3663/scouting_app/data/Comments.java
Fixes #288
also fix a screen rotation issue using the BACK button.
> Fix Bug 288

- app/src/main/java/com/team3663/scouting_app/activities/PostMatch.java
- app/src/main/java/com/team3663/scouting_app/activities/SubmitData.java
- app/src/main/java/com/team3663/scouting_app/config/Constants.java
- app/src/main/java/com/team3663/scouting_app/utility/Logger.java
- app/src/main/java/com/team3663/scouting_app/utility/achievements/Achievements.java
- app/src/main/res/layout/submit_data.xml
Had to move the closing of the logger to the SubmitData page since we get achievements there and need to log it first.
Also needed to number the achievements so we can log the ID only.
Adjusted the layout to fit the achievement text.
> Jeff fix303

- app/src/main/java/com/team3663/scouting_app/activities/QRCode.java
- app/src/main/java/com/team3663/scouting_app/config/Constants.java
I already updated the scanner app to look for this.  Works great (faster than the timer - more reliable).  You can even paste in multiple files and it handles each one.  (helpful if we use the scanner in "storage" mode and then transmit them all at once to the scanner app.
> add EOF to QR code

- app/src/main/assets/input_data/Competitions.csv
- app/src/main/java/com/team3663/scouting_app/activities/PostMatch.java
- app/src/main/java/com/team3663/scouting_app/activities/SubmitData.java
- app/src/main/java/com/team3663/scouting_app/config/Constants.java
- app/src/main/java/com/team3663/scouting_app/utility/Logger.java
- app/src/main/java/com/team3663/scouting_app/utility/achievements/Achievements.java
- app/src/main/java/com/team3663/scouting_app/utility/achievements/RuleAlgaePickup.java
- app/src/main/java/com/team3663/scouting_app/utility/achievements/RuleClimbed.java
- app/src/main/java/com/team3663/scouting_app/utility/achievements/RuleCompetition.java
Swiss Army Bot
and 
World Renowned Scouter
> Adriel achievements

- app/src/main/java/com/team3663/scouting_app/activities/AppLaunch.java
Now we'll ignore a blank line anywhere in the input data (config) files (as long as it doesn't have a comma...) :)
fixes #426
resolves #426
closes #426
> handle blank lines in data files
